application:
  name: notification-service
server:
  port: 0
zipkin:
  base-url: http://localhost:9411
sleuth:
  sampler:
    probability: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
