eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
          route:
              RouteDefinitionLocator: INFO

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes[0]:
        id: product-service
        uri: lb://product-service
        predicates[0]: Path=/api/product
      routes[1]:
        id: order-service
        uri: lb://order-service
        predicates[0]: Path=/api/order
      routes[2]:
        id: discovery-service
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/web
        filters[0]: SetPath=/
      routes[3]:
        id: discovery-service-static
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/**
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
server:
  port : 8089

